### PR TITLE
Allow window to be maximized

### PR DESCRIPTION
**Pull request by ZhiyueYi**
Allow window to be maximized

maximize

Btw, amazing project!!! I love it!!

### CODE REVIEW

**Comment by PuruVJ** [comment]
This is amazing!!!! I'd love to have it merged. Though the moving the windows around thing is gonna be fixed. Overall great work!! Thank you for the help!

**Comment by ZhiyueYi** [comment]
@PuruVJ now it gets fixed. Though it's a little bit hacky :p

**Comment by PuruVJ** [comment]
Its perfect!!! Will review and merge soon.

**Comment by PuruVJ** [comment]
The code looks really good to me. I wouldn't have been able to write this complex code. Great work!!

Thank you for contributing!

**Comment by PuruVJ** [comment]
Hi, I'm sorry, I had to revert it back. Seems it didn't have the latest codebase when you started working on this PR. WOuld you mind doing a `git pull origin main`, and then making a PR? Really sorry for the inconvenience 😅😅

**Comment by PuruVJ** [comment]
never mind, I got confused. Its perfectly fine

**Pull request merged**
