### PR TITLE
Make app windows resizable & Make scrollbars better looking

### PR DESCRIPTION
**Pull request by Froggo8311**
Make app windows resizable by enforcing the `resize` style property and set minimum window sizes.

### CODE REVIEW

**Comment by Froggo8311** [comment]
Hol on

**Comment by Froggo8311** [comment]
then try again dummy

**Comment by Froggo8311** [comment]
dang. thought that would work to make it look better

**Comment by PuruVJ** [comment]
Thank you!

I intended to make a script for resizabilitty in all directions but for now this would do

**Pull request merged**
