### PR TITLE
🚪Basic Window 

### LINKED ISSUE #46: Create basic window
- Should open on clicking on any app icon in dock
- should have traffic light buttons on it
- Look like MacOS Window
- Draggable
- Resizable
- For now, put "Windows coming soon" in them

### PR DESCRIPTION
**Pull request by PuruVJ**
Closes #46

### CODE REVIEW

**Comment by preetjdp** [comment]
The `view source` icon seems broken, not sure if this is known

Screenshot 2021-03-12 at 1 35 58 PM

**Comment by PuruVJ** [comment]
> The `view source` icon seems broken, not sure if this is known
> 
> Screenshot 2021-03-12 at 1 35 58 PM

Hi @preetjdp. Thanks for checking this out.

Problem seems to arise from the renaming of the view-source files. a Hard Reload should fix the issue

**Comment by preetjdp** [comment]
> a Hard Reload should fix the issue

Ah, yes that fixed it ✅

**Comment by PuruVJ** [comment]
> > a Hard Reload should fix the issue
> 
> Ah, yes that fixed it ✅

Great!! Enjoy the Window experience while I improve it commit by commit 😉

**Comment by PuruVJ** [comment]
Last commit enabled window stacking. If you have multiple windows, clicking on anyone, and it comes forward.

**Pull request merged**
